package dnsguard

import (
	"context"
	"errors"
	"slices"
	"strings"
	"testing"
)

func TestDetectDNSStack(t *testing.T) {
	const (
		stub      = "# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).\nnameserver 127.0.0.53\noptions edns0 trust-ad\n"
		uplink    = "# This is /run/systemd/resolve/resolv.conf managed by man:systemd-resolved(8).\nnameserver 192.168.1.1\n"
		nm        = "# Generated by NetworkManager\nsearch lan\nnameserver 192.168.1.1\n"
		openres   = "# Generated by resolvconf\nnameserver 192.168.1.1\n"
		debianRC  = "# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)\n#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN\nnameserver 192.168.1.1\n"
		netconfig = "### /etc/resolv.conf file autogenerated by netconfig!\n#\n# Before you change this file manually, consider to define the\nnameserver 192.168.1.1\n"
		plain     = "nameserver 1.1.1.1\n# Generated by resolvconf, but not on top\n"
		wsl       = "# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:\n# [network]\n# generateResolvConf = false\nnameserver 172.23.64.1\n"
	)
	for _, c := range []struct {
		name string
		env  linuxDNSEnv
		want dnsStack
	}{
		{"Ubuntu: resolved stub", linuxDNSEnv{ResolvConf: []byte(stub), Link: "../run/systemd/resolve/stub-resolv.conf", ResolvedRunning: true, Resolvconf: true}, stackResolved},
		{"resolved stub, resolved down", linuxDNSEnv{ResolvConf: []byte(stub), Link: "../run/systemd/resolve/stub-resolv.conf"}, stackFile},
		{"resolved in uplink mode", linuxDNSEnv{ResolvConf: []byte(uplink), ResolvedRunning: true, Resolvconf: true}, stackFile},
		{"NetworkManager writes the file", linuxDNSEnv{ResolvConf: []byte(nm)}, stackFile},
		{"openresolv (Void, Alpine, Arch)", linuxDNSEnv{ResolvConf: []byte(openres), Resolvconf: true}, stackResolvconf},
		{"Debian resolvconf, linked", linuxDNSEnv{ResolvConf: []byte(debianRC), Link: "/run/resolvconf/resolv.conf", Resolvconf: true}, stackResolvconf},
		{"resolvconf signature, command gone", linuxDNSEnv{ResolvConf: []byte(openres)}, stackFile},
		{"openSUSE netconfig", linuxDNSEnv{ResolvConf: []byte(netconfig), Netconfig: true}, stackNetconfig},
		{"netconfig file, command gone", linuxDNSEnv{ResolvConf: []byte(netconfig)}, stackFile},
		{"hand-written", linuxDNSEnv{ResolvConf: []byte(plain), Resolvconf: true, Netconfig: true}, stackFile},
		{"missing", linuxDNSEnv{}, stackFile},
		{"WSL's generated file", linuxDNSEnv{ResolvConf: []byte(wsl), Link: "/mnt/wsl/resolv.conf", Resolvconf: true}, stackFile},
	} {
		if got := detectDNSStack(c.env); got != c.want {
			t.Errorf("%s: %q, want %q", c.name, got, c.want)
		}
	}
}

func TestLinuxResolvconf(t *testing.T) {
	h := newLinuxHarness(t, false, "")
	h.stack = stackResolvconf
	ctx := context.Background()
	if err := h.g.Apply(ctx, Config{Interface: "coreshift", Servers: tunDNS}); err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(h.commands, []string{"resolvconf -a tun.coreshift -m 0 -x"}) || !strings.Contains(h.inputs[0], "nameserver 172.19.0.2") {
		t.Fatalf("commands %v, input %q", h.commands, h.inputs)
	}
	h.commands = nil
	if err := h.g.Revert(ctx); err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(h.commands, []string{"resolvconf -d tun.coreshift"}) {
		t.Fatalf("revert commands %v", h.commands)
	}
}

// Debian's resolvconf has no -x or -m: the plain record is added instead.
func TestLinuxResolvconfDebian(t *testing.T) {
	h := newLinuxHarness(t, false, "")
	h.stack = stackResolvconf
	h.g.runInput = func(_ context.Context, _ []byte, name string, args ...string) error {
		h.commands = append(h.commands, name+" "+strings.Join(args, " "))
		if slices.Contains(args, "-x") {
			return errors.New("unknown option -x")
		}
		return nil
	}
	if err := h.g.Apply(context.Background(), Config{Interface: "coreshift", Servers: tunDNS}); err != nil {
		t.Fatal(err)
	}
	if want := []string{"resolvconf -a tun.coreshift -m 0 -x", "resolvconf -a tun.coreshift"}; !slices.Equal(h.commands, want) {
		t.Fatalf("commands %v", h.commands)
	}
}

func TestLinuxNetconfig(t *testing.T) {
	h := newLinuxHarness(t, false, "")
	h.stack = stackNetconfig
	ctx := context.Background()
	if err := h.g.Apply(ctx, Config{Interface: "coreshift", Servers: tunDNS}); err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(h.commands, []string{"netconfig modify -s coreshift -i coreshift"}) ||
		h.inputs[0] != "INTERFACE='coreshift'\nDNSSERVERS='172.19.0.2'\nDNSSEARCH=''\n" {
		t.Fatalf("commands %v, input %q", h.commands, h.inputs)
	}
	h.commands = nil
	h.g.Revert(ctx)
	if !slices.Equal(h.commands, []string{"netconfig remove -s coreshift -i coreshift"}) {
		t.Fatalf("revert commands %v", h.commands)
	}
}

func TestLinuxFirewalld(t *testing.T) {
	h := newLinuxHarness(t, true, "")
	h.fw = true
	ctx := context.Background()
	if err := h.g.Apply(ctx, Config{Interface: "coreshift", Servers: tunDNS}); err != nil {
		t.Fatal(err)
	}
	if h.commands[0] != "firewall-cmd --zone=trusted --change-interface=coreshift" {
		t.Fatalf("commands %v", h.commands)
	}
	h.commands = nil
	if err := h.g.Revert(ctx); err != nil {
		t.Fatal(err)
	}
	if !slices.Contains(h.commands, "firewall-cmd --zone=trusted --remove-interface=coreshift") {
		t.Fatalf("revert commands %v", h.commands)
	}
	if h.g.journal.Len() != 0 {
		t.Fatal("journal not empty")
	}
}

// The new kinds of change are checked like the others before the daemon,
// as root, runs anything for them.
func TestLinuxRecoverRejectsForgedCommands(t *testing.T) {
	for name, entry := range map[string]struct {
		kind string
		data any
	}{
		"resolvconf record of another kind": {kindResolvconf, resolvconfChange{Record: "eth0"}},
		"resolvconf option":                 {kindResolvconf, resolvconfChange{Record: "tun.-x"}},
		"resolvconf long":                   {kindResolvconf, resolvconfChange{Record: "tun.abcdefghijklmnopq"}},
		"netconfig option":                  {kindNetconfig, netconfigChange{Interface: "--help"}},
		"firewalld other zone":              {kindFirewalld, firewalldChange{Interface: "coreshift", Zone: "public"}},
		"firewalld zone option":             {kindFirewalld, firewalldChange{Interface: "coreshift", Zone: "trusted --panic-on"}},
		"firewalld iface option":            {kindFirewalld, firewalldChange{Interface: "--panic-on", Zone: "trusted"}},
	} {
		t.Run(name, func(t *testing.T) {
			h := newLinuxHarness(t, false, "")
			if err := h.g.journal.Record(entry.kind, entry.data); err != nil {
				t.Fatal(err)
			}
			if err := h.g.Recover(context.Background()); !errors.Is(err, ErrRejected) {
				t.Fatalf("Recover err = %v, want ErrRejected", err)
			}
			if len(h.commands) != 0 {
				t.Fatalf("ran %v", h.commands)
			}
			if h.g.journal.Len() != 0 {
				t.Fatal("rejected entry kept")
			}
		})
	}
}

func TestFirstComments(t *testing.T) {
	got := firstComments([]byte("\n# Generated by NetworkManager\n; old style\nnameserver 1.1.1.1\n# later\n"))
	if got != "# generated by networkmanager\n; old style\n" {
		t.Errorf("firstComments = %q", got)
	}
}
