package dnsguard

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"strings"
)

// This file holds the Linux guard's logic. Commands and the resolv.conf path
// are injected so it can be tested on any OS; guard_linux.go wires it up.

const (
	kindResolvedLink = "linux.resolved"
	kindResolvConf   = "linux.resolvconf"
)

type commandRunner func(ctx context.Context, name string, args ...string) error

type resolvedLinkChange struct {
	Interface string `json:"interface"`
}

type resolvConfChange struct {
	Path    string      `json:"path"`
	Existed bool        `json:"existed"`
	Symlink string      `json:"symlink,omitempty"`
	Content []byte      `json:"content,omitempty"`
	Mode    fs.FileMode `json:"mode,omitempty"`
	// Written is what we put there; if the file differs at undo time someone
	// else (NetworkManager, the user) owns it now and we leave it alone.
	Written []byte `json:"written"`
}

type linuxGuard struct {
	journal        *Journal
	run            commandRunner
	resolvConfPath string
	// useResolved reports whether systemd-resolved serves the system's DNS.
	useResolved func() bool
	linkExists  func(name string) bool
}

func (g *linuxGuard) Apply(ctx context.Context, cfg Config) error {
	if err := cfg.validate(); err != nil {
		return err
	}
	if err := g.Revert(ctx); err != nil {
		return fmt.Errorf("dnsguard: revert previous state: %w", err)
	}
	var err error
	if g.useResolved() {
		err = g.applyResolved(ctx, cfg)
	} else {
		err = g.applyResolvConf(cfg)
	}
	if err != nil {
		return errors.Join(err, g.Revert(ctx))
	}
	return nil
}

func (g *linuxGuard) Revert(ctx context.Context) error {
	if g.journal.Len() == 0 {
		return nil
	}
	return g.journal.Undo(func(c Change) error { return g.undo(ctx, c) })
}

func (g *linuxGuard) Recover(ctx context.Context) error { return g.Revert(ctx) }

// applyResolved gives the TUN link our servers and the "~." routing domain,
// so resolved sends every query there.
func (g *linuxGuard) applyResolved(ctx context.Context, cfg Config) error {
	if err := g.journal.Record(kindResolvedLink, resolvedLinkChange{Interface: cfg.Interface}); err != nil {
		return err
	}
	servers := strings.Fields(joinAddrs(cfg.Servers, " "))
	for _, args := range [][]string{
		append([]string{"dns", cfg.Interface}, servers...),
		{"domain", cfg.Interface, "~."},
		{"default-route", cfg.Interface, "yes"},
	} {
		if err := g.run(ctx, "resolvectl", args...); err != nil {
			return fmt.Errorf("dnsguard: resolvectl %s: %w", strings.Join(args, " "), err)
		}
	}
	_ = g.run(ctx, "resolvectl", "flush-caches") // best effort; stale entries expire anyway
	return nil
}

func (g *linuxGuard) applyResolvConf(cfg Config) error {
	ch, err := snapshotFile(g.resolvConfPath)
	if err != nil {
		return fmt.Errorf("dnsguard: read %s: %w", g.resolvConfPath, err)
	}
	ch.Written = renderResolvConf(cfg)
	if err := g.journal.Record(kindResolvConf, ch); err != nil {
		return err
	}
	if ch.Symlink != "" {
		// Replace the link itself, not the file it points to.
		if err := os.Remove(ch.Path); err != nil {
			return fmt.Errorf("dnsguard: replace %s: %w", ch.Path, err)
		}
	}
	if err := writeFileAtomic(ch.Path, ch.Written, 0o644); err != nil {
		return fmt.Errorf("dnsguard: write %s: %w", ch.Path, err)
	}
	return nil
}

func (g *linuxGuard) undo(ctx context.Context, c Change) error {
	switch c.Kind {
	case kindResolvedLink:
		var ch resolvedLinkChange
		if err := json.Unmarshal(c.Data, &ch); err != nil {
			return err
		}
		// resolved drops per-link settings together with the link.
		if !g.linkExists(ch.Interface) {
			return nil
		}
		return g.run(ctx, "resolvectl", "revert", ch.Interface)
	case kindResolvConf:
		var ch resolvConfChange
		if err := json.Unmarshal(c.Data, &ch); err != nil {
			return err
		}
		return restoreResolvConf(ch)
	}
	// Unknown kinds come from a newer build; this one cannot undo them.
	return nil
}

func renderResolvConf(cfg Config) []byte {
	var b bytes.Buffer
	b.WriteString("# Generated by CoreShift while the tunnel is up; the original is restored on disconnect.\n")
	for _, s := range cfg.Servers {
		fmt.Fprintf(&b, "nameserver %s\n", s)
	}
	return b.Bytes()
}

func snapshotFile(path string) (resolvConfChange, error) {
	ch := resolvConfChange{Path: path}
	fi, err := os.Lstat(path)
	if errors.Is(err, fs.ErrNotExist) {
		return ch, nil
	}
	if err != nil {
		return ch, err
	}
	ch.Existed = true
	if fi.Mode()&fs.ModeSymlink != 0 {
		ch.Symlink, err = os.Readlink(path)
		return ch, err
	}
	ch.Mode = fi.Mode().Perm()
	ch.Content, err = os.ReadFile(path)
	return ch, err
}

func restoreResolvConf(ch resolvConfChange) error {
	cur, err := os.ReadFile(ch.Path)
	switch {
	case errors.Is(err, fs.ErrNotExist):
		// Gone; put the original back.
	case err != nil:
		return err
	case !bytes.Equal(cur, ch.Written):
		// Either we crashed before writing it, or someone else replaced it since.
		return nil
	}
	if err := os.Remove(ch.Path); err != nil && !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	if !ch.Existed {
		return nil
	}
	if ch.Symlink != "" {
		return os.Symlink(ch.Symlink, ch.Path)
	}
	return writeFileAtomic(ch.Path, ch.Content, ch.Mode)
}
