package dnsguard

import (
	"bytes"
	"strings"
)

// dnsStack is what manages the system's DNS on a Linux machine, and so how
// the guard redirects it. Detected anew on every Apply: it is the state of
// the machine now that counts.
type dnsStack string

const (
	// stackResolved: systemd-resolved, with /etc/resolv.conf pointing at
	// its stub (Ubuntu, Fedora; NetworkManager on top of it). Per-link DNS
	// with the "~." routing domain.
	stackResolved dnsStack = "systemd-resolved"
	// stackResolvconf: resolvconf or openresolv writes /etc/resolv.conf
	// from records per interface (Debian with resolvconf, Void, Alpine,
	// Gentoo, Arch with openresolv). We add a record of our own.
	stackResolvconf dnsStack = "resolvconf"
	// stackNetconfig: openSUSE's netconfig writes /etc/resolv.conf from
	// what services hand it. We hand it our servers as a service.
	stackNetconfig dnsStack = "netconfig"
	// stackFile: nothing we can talk to, or NetworkManager writing the file
	// itself: we write /etc/resolv.conf, and Keep writes it again when
	// someone replaces it.
	stackFile dnsStack = "resolv.conf"
)

// linuxDNSEnv is what the detection looks at; guard_linux.go gathers it.
type linuxDNSEnv struct {
	// ResolvConf is /etc/resolv.conf's contents (through a symlink), and
	// Link its symlink target, "" for a plain file.
	ResolvConf []byte
	Link       string
	// ResolvedRunning: systemd-resolved answers (its varlink socket is
	// there) and resolvectl is installed.
	ResolvedRunning bool
	// Resolvconf, Netconfig: the commands are installed. On systems with
	// systemd-resolved, resolvconf may be resolvectl in disguise; resolved
	// is checked first.
	Resolvconf bool
	Netconfig  bool
}

// detectDNSStack picks how to redirect DNS in env.
func detectDNSStack(env linuxDNSEnv) dnsStack {
	if env.ResolvedRunning && usesResolvedStub(env.ResolvConf) {
		return stackResolved
	}
	head := firstComments(env.ResolvConf)
	if env.Netconfig && strings.Contains(head, "netconfig") {
		return stackNetconfig
	}
	if env.Resolvconf && (strings.Contains(env.Link, "/resolvconf/") || strings.Contains(head, "resolvconf")) {
		return stackResolvconf
	}
	return stackFile
}

// firstComments returns the leading comment lines of a resolv.conf,
// lowercased: managers sign the files they write there ("# Generated by
// NetworkManager", "### /etc/resolv.conf file autogenerated by netconfig!",
// "# Generated by resolvconf", "... generated by resolvconf(8)").
func firstComments(b []byte) string {
	var out strings.Builder
	for _, line := range bytes.Split(b, []byte("\n")) {
		line = bytes.TrimSpace(line)
		if len(line) == 0 {
			continue
		}
		if line[0] != '#' && line[0] != ';' {
			break
		}
		out.Write(bytes.ToLower(line))
		out.WriteByte('\n')
	}
	return out.String()
}

// resolvconfRecord is the name of our record with resolvconf: Debian's
// resolvconf puts records matching "tun*" before those of the physical
// interfaces (/etc/resolvconf/interface-order), openresolv takes any name.
func resolvconfRecord(iface string) string { return "tun." + iface }

// renderNetconfig is what netconfig is handed on stdin for our service.
func renderNetconfig(cfg Config) []byte {
	return []byte("INTERFACE='" + cfg.Interface + "'\nDNSSERVERS='" + joinAddrs(cfg.Servers, " ") + "'\nDNSSEARCH=''\n")
}

// firewalldZone is where the TUN interface goes while the tunnel is up:
// the TUN layer answers connections from the system through it, which
// firewalld's default zones would refuse as new inbound traffic.
const firewalldZone = "trusted"
