# Builds dist\coreshift-<version>-b<build>.apk: the Flutter app with the Go
# engine (bound by gomobile into an AAR) and the proxy cores for 64-bit ARM.
#
#   powershell -ExecutionPolicy Bypass -File packaging\android\build.ps1
#
# With -Abi x86_64 it builds coreshift-<version>-b<build>-x86_64.apk for the
# Android emulator on a PC instead: its ARM translation cannot run the Go
# engine. Such an APK is for testing, not for phones, and does not update
# itself: the releases are for phones.
#
# The phone's APK updates itself from the private releases with the
# read-only token of %USERPROFILE%\.coreshift\releases-token, built in as
# for the Windows service (see packaging\README.md).
#
# Needs go, gomobile (go install golang.org/x/mobile/cmd/gomobile@latest),
# flutter, git and the Android SDK with NDK 28.2 (%LOCALAPPDATA%\Android\Sdk).
#
# Version, build number and commit come from VERSION and git, as for the
# Windows installer. The cores come from engine\testdata\bin\android-arm64
# (libxray.so, libsingbox.so, libmihomo.so), for x86_64 from
# engine\testdata\bin\android-x86_64, or from -Cores. The APK is
# signed with the key from %USERPROFILE%\.coreshift\android-signing.properties;
# without it, with the debug key (such an APK cannot be updated by one
# signed with the release key).
param(
    [string]$Cores,
    [string]$OutDir,
    [ValidateSet('arm64-v8a', 'x86_64')]
    [string]$Abi = 'arm64-v8a'
)
$ErrorActionPreference = 'Stop'
$root = (Resolve-Path "$PSScriptRoot\..\..").Path
# The names each tool gives the ABI.
$goArch, $flutterArch, $coresDir = if ($Abi -eq 'x86_64') { 'amd64', 'android-x64', 'android-x86_64' } else { 'arm64', 'android-arm64', 'android-arm64' }
if (-not $Cores) { $Cores = Join-Path $root "engine\testdata\bin\$coresDir" }
if (-not $OutDir) { $OutDir = Join-Path $root 'dist' }

function Step($text) { Write-Host "==> $text" -ForegroundColor Cyan }

function Check($what) {
    if ($LASTEXITCODE -ne 0) { throw "$what failed (exit code $LASTEXITCODE)" }
}

$version = (Get-Content "$root\VERSION" -Raw).Trim()
if ($version -notmatch '^\d+\.\d+\.\d+$') { throw "VERSION must look like 1.2.3, not '$version'" }
Push-Location $root
try {
    $ErrorActionPreference = 'Continue'
    git rev-parse --verify --quiet HEAD 2>$null | Out-Null
    $haveRepo = $LASTEXITCODE -eq 0
    $ErrorActionPreference = 'Stop'
    if (-not $haveRepo) { throw "$root is not a git repository with commits: the build number and the commit come from git" }
    $build = [int](git rev-list --count HEAD)
    $commit = (git rev-parse --short=7 HEAD).Trim()
    if (git status --porcelain) { $commit += '-dirty' }
} finally { Pop-Location }
$tag = "$version-b$build"
if ($commit.EndsWith('-dirty')) { $tag += '-dirty' }
if ($Abi -ne 'arm64-v8a') { $tag += "-$Abi" }

$sdk = if ($env:ANDROID_HOME) { $env:ANDROID_HOME } else { Join-Path $env:LOCALAPPDATA 'Android\Sdk' }
$ndk = Get-ChildItem "$sdk\ndk" -Directory -ErrorAction SilentlyContinue | Sort-Object Name | Select-Object -Last 1
if (-not $ndk) { throw "no NDK in $sdk\ndk (see packaging\README.md)" }
$env:ANDROID_HOME = $sdk
$env:ANDROID_NDK_HOME = $ndk.FullName
$env:Path = "$env:USERPROFILE\go\bin;$env:Path"
foreach ($c in 'go', 'gomobile', 'flutter') {
    if (-not (Get-Command $c -ErrorAction SilentlyContinue)) { throw "$c not found" }
}
foreach ($f in 'libxray.so', 'libsingbox.so', 'libmihomo.so') {
    if (-not (Test-Path "$Cores\$f")) { throw "$Cores\$f is missing (see packaging\README.md)" }
}

Step "engine $version build $build ($commit)"
# The releases token, in a generated file that exists only during the
# build, as in packaging\windows\build.ps1.
$tokenGo = "$root\engine\internal\selfupdate\token_gen.go"
if ($Abi -eq 'arm64-v8a') {
    $tokenFile = Join-Path $env:USERPROFILE '.coreshift\releases-token'
    $releasesToken = $env:CORESHIFT_RELEASES_TOKEN
    if (-not $releasesToken -and (Test-Path $tokenFile)) { $releasesToken = (Get-Content $tokenFile -Raw).Trim() }
    if ($releasesToken) {
        if ($releasesToken -notmatch '^(github_pat_|ghp_)[A-Za-z0-9_]+$') { throw "the releases token in $tokenFile does not look like a GitHub token" }
        [IO.File]::WriteAllText($tokenGo, "// Generated by build.ps1; never commit.`n`npackage selfupdate`n`nfunc init() { token = `"$releasesToken`" }`n")
    } else {
        Write-Warning "no releases token ($tokenFile): this APK cannot update itself from the private releases"
    }
}
$pkg = 'coreshift/engine/internal/service'
$aar = "$root\app\android\app\libs\coreshift-engine.aar"
New-Item -ItemType Directory (Split-Path $aar) -Force | Out-Null
Push-Location "$root\engine"
try {
    gomobile bind "-target=android/$goArch" -androidapi 24 -tags with_gvisor -javapkg dev.coreshift -trimpath `
        -ldflags "-s -w -X $pkg.Version=$version -X $pkg.Build=$build -X $pkg.Commit=$commit" -o $aar ./mobile
    Check 'gomobile bind'
} finally {
    Pop-Location
    Remove-Item $tokenGo -ErrorAction SilentlyContinue
}

Step "cores from $Cores"
$jni = "$root\app\android\app\src\main\jniLibs\$Abi"
New-Item -ItemType Directory $jni -Force | Out-Null
Copy-Item "$Cores\lib*.so" $jni -Force
$env:CORESHIFT_ABI = $Abi # build.gradle.kts packs this ABI alone

Step 'app'
Push-Location "$root\app"
try {
    flutter build apk --release --target-platform $flutterArch --build-name $version --build-number $build `
        "--dart-define=CORESHIFT_VERSION=$version" "--dart-define=CORESHIFT_BUILD=$build" "--dart-define=CORESHIFT_COMMIT=$commit"
    Check 'flutter build apk'
} finally { Pop-Location }

New-Item -ItemType Directory $OutDir -Force | Out-Null
$apk = Join-Path $OutDir "coreshift-$tag.apk"
Copy-Item "$root\app\build\app\outputs\flutter-apk\app-release.apk" $apk -Force
Write-Host "Done: $apk" -ForegroundColor Green
