package msg

// ru is every code's Russian template: the text the journal shows and older
// apps get. app/lib/l10n/engine_strings.dart has the same templates, in
// Russian and in English; its test reads this file, so keep one entry a
// line, "code": "template", and no escapes in the templates.
var ru = map[string]string{
	CodeRaw: "{text}",

	// Why a probe failed (reach.go, checkup.go).
	"net.timeout":            "нет ответа",
	"net.refused":            "соединение отклонено",
	"net.unreachable":        "адрес недоступен",
	"net.reset":              "соединение сброшено",
	"net.host_err":           "{host} — {err}",
	"net.status":             "ответ {status}",
	"net.empty_answer":       "пустой ответ",
	"net.nothing_downloaded": "ничего не скачалось",
	"dns.not_found":          "имя не найдено",

	// Who is at fault when nothing gets through (reach.go): the "server"
	// event's Line.
	"reach.server_up":   "сервер {addr} отвечает напрямую, но соединение через него не проходит",
	"reach.offline":     "не отвечают ни сервер, ни известные узлы: {errs}",
	"reach.server_down": "сервер {addr} не отвечает напрямую ({err}), а интернет работает",
	"reach.no_bypass":   "не удалось проверить, сервер виноват или сеть: не найден сетевой интерфейс в обход туннеля",
	"reach.udp_silent":  "интернет работает, а сервер по UDP на ping не отвечает: жив ли он, не понять",
	"reach.unknown":     "интернет работает, а проверить сервер напрямую не удалось",

	// A server's name that did not resolve (host.go): a failed connection.
	"server.resolve.not_found": "адрес сервера {host} не найден в DNS: имя неверное или сервер убран, обновите подписку",
	"server.resolve.timeout":   "DNS не ответил, когда узнавали адрес сервера {host}",
	"server.resolve.failed":    "не удалось узнать адрес сервера {host}: {err}",

	"failover.none": "ни один другой сервер подписки не отвечает",

	// The system's DNS and the TUN layer (connect.go, coreapply.go).
	"dns.keep_failed":      "не удалось снова направить системный DNS в туннель: {err}",
	"dns.network_changed":  "сеть сменилась: DNS {old} больше нет, теперь система спрашивает {new}; переподключаюсь",
	"dns.system_missing":   "системный DNS не найден ({why}): прямые адреса узнаю через {direct}",
	"dns.system_none":      "система не назвала ни одного",
	"dns.revert_failed":    "не удалось восстановить системный DNS: {err}",
	"tun.ipv6_refused":     "интерфейс не принял IPv6 ({err}): туннель только IPv4",
	"tun.update_refused":   "sing-box {version} не принял настройки слоя TUN ({err}): слой остаётся на прежней версии до следующего подключения",
	"tun.update_rollback":  "слой TUN не запустился на sing-box {version} ({err}): вернул прежнюю версию до следующего подключения",
	"tun.update_reconnect": "слой TUN не запустился на sing-box {version} ({err}): переподключаюсь",

	// Direct connections that do not get through (direct.go).
	"direct.blocked":                 "Прямые соединения не проходят ({n} за минуту), а через VPN всё работает: похоже, сеть пропускает только белый список или российские сайты отсюда недоступны. {advice}",
	"direct.advice.none":             "",
	"direct.advice.all":              "Включите «Всё через VPN».",
	"direct.advice.russia":           "Выключите «Российские сайты напрямую».",
	"direct.advice.all_russia":       "Включите «Всё через VPN» и выключите «Российские сайты напрямую».",
	"direct.advice.all_lists":        "Включите «Всё через VPN»; проверьте и свои списки «напрямую».",
	"direct.advice.russia_lists":     "Выключите «Российские сайты напрямую»; проверьте и свои списки «напрямую».",
	"direct.advice.all_russia_lists": "Включите «Всё через VPN» и выключите «Российские сайты напрямую»; проверьте и свои списки «напрямую».",
	"direct.advice.lists":            "Уберите из своих списков «напрямую» то, что здесь не открывается.",

	// Rule sets (georules.go, rulesets.go): a "rules" event's Error.
	"rules.source.own":       "своей ссылки",
	"rules.fallback.failed":  "база {set} из {src} не загрузилась: {err}, пока работает встроенная {tag}",
	"rules.fallback.pending": "база {set} из {src} ещё загружается, пока работает встроенная {tag}",
	"rules.skipped.failed":   "правило «{match} → {action}» пропущено: база из {src} не загрузилась: {err}",
	"rules.skipped.pending":  "правило «{match} → {action}» пропущено: база из {src} ещё загружается, правило заработает после переподключения",
	"rules.action.proxy":     "через VPN",
	"rules.action.direct":    "напрямую",
	"rules.action.block":     "блокировать",
	"rules.kept":             "база {set} не обновилась, работает прежняя: {err}",
	"rules.pending":          "база {set} ещё загружается, до переподключения {lost}",
	"rules.failed":           "база {set} не загрузилась, {lost}: {err}",
	"rules.damaged":          "база {set} испорчена: {err}",
	"rules.write_failed":     "база {set} не записалась: {err}",
	"rules.lost.sites":       "её сайты пойдут через туннель",
	"rules.lost.geoip_ru":    "российские адреса пойдут через туннель",
	"rules.lost.media_ru":    "заблокированные СМИ на .ru могут не открыться",
	"rules.lost.ru_blocked":  "заблокированные сайты на .ru могут не открыться",
	"rules.lost.ads":         "реклама не блокируется",
	"rules.lost.google":      "Google пойдёт через туннель по встроенному списку",

	// The journal's own lines among the cores' output (log.go, loggroup.go).
	"log.dns_dead":     "DNS через VPN не отвечает: сервер недоступен",
	"log.stale_fakeip": "программа обратилась по адресу Fake-IP из прежнего подключения: она запросит адрес заново и соединится — обычно в первую минуту после перезапуска CoreShift",
	"log.repeats":      "{line} — ещё {n} {n|раз|раза|раз} за {period}",
	"time.min":         "{n} мин",
	"time.sec":         "{n} с",

	// The network (netinfo.go, netwatch.go).
	"net.kind.wifi":   "Wi-Fi",
	"net.kind.mobile": "мобильная сеть",
	"net.kind.cable":  "кабель",
	"net.kind.usb":    "USB-модем",
	"net.label":       "{kind} ({name})",
	"net.ipv6.yes":    "IPv6 есть",
	"net.ipv6.no":     "IPv6 нет",
	"net.dns_count":   "DNS сети: {n}",
	"net.info":        "сеть: {net}",
	"net.changed":     "сеть сменилась: {was} → {now}",
	"net.waiting":     "сети нет: подключусь, как только она появится",
	"net.lost":        "сеть пропала: соединение ждёт её, ядра и сервер не меняются",
	"net.back":        "сеть вернулась",
	"net.appeared":    "сеть появилась",
	"net.reconnect":   "сеть вернулась, но связь через сервер не восстановилась: переподключаюсь",

	// The proxy without the TUN layer (proxymode.go).
	"proxy.up.system":    "прокси SOCKS5 и HTTP на {addr} открыт; системный прокси настроит приложение",
	"proxy.up.manual":    "прокси SOCKS5 и HTTP на {addr} открыт для программ, настроенных на него",
	"proxy.up.no_auth":   "прокси без VPN на {addr}: нет логина и пароля, приложения не смогут им пользоваться",
	"proxy.up.open_http": "прокси без VPN на {addr}: SOCKS5 по логину и паролю, HTTP без пароля — им может пользоваться любое приложение на телефоне",
	"proxy.up.auth":      "прокси без VPN на {addr}: SOCKS5 и HTTP по логину и паролю из настроек",
	"proxy.down":         "прокси закрыт",
	"proxy.down.android": "прокси без VPN выключен",

	// Why a connection changes without the app's buttons: "action" events
	// (lifecycle.go, appupdate.go, mobile/engine.go).
	"action.autostart":          "подключить (автозапуск)",
	"action.autostart_node":     "подключить: {name} (автозапуск)",
	"action.resume":             "служба перезапустилась посреди соединения, подключаюсь снова",
	"action.resume_node":        "служба перезапустилась посреди соединения, подключаюсь снова: {name}",
	"action.update_resume":      "обновление прервало соединение, подключаюсь снова",
	"action.update_resume_node": "обновление прервало соединение, подключаюсь снова: {name}",
	"action.retry":              "{what}, ещё одна попытка",
	"action.connect":            "подключить",
	"action.connect_node":       "подключить: {name}",
	"action.disconnect":         "отключить",
	"action.from_tile":          "{what} (плитка)",
	"action.from_notification":  "{what} (уведомление)",
	"announce.line":             "объявление от «{name}»: {text}",
	"update.mirror_checked":     "{site} недоступен, проверено через {via}",
	"update.mirror_downloaded":  "{site} недоступен, обновление скачано через {via}",
	"update.site.folder":        "папка",
	"update.disconnecting":      "отключаюсь, чтобы установить версию {version}",
	"update.installer_failed":   "установщик не запустился, подключаюсь снова",
	"update.restart_failed":     "не удалось запустить приложение после обновления: {err}",

	// The checkup (checkup.go): the steps' titles and details.
	"checkup.step.network":         "Сеть устройства",
	"checkup.step.internet":        "Интернет напрямую",
	"checkup.step.dns":             "DNS сети",
	"checkup.step.server":          "Сервер",
	"checkup.step.tunnel":          "Связь через VPN",
	"checkup.step.tunnel-dns":      "DNS через VPN",
	"checkup.step.leak":            "Утечка DNS",
	"checkup.step.speed":           "Скорость",
	"checkup.step.direct":          "Прямые соединения",
	"checkup.not_connected":        "VPN не подключён",
	"checkup.no_bypass":            "не найден сетевой интерфейс в обход туннеля: напрямую не проверить",
	"checkup.network.none":         "устройство не подключено к сети: нет Wi-Fi, кабеля или мобильного интернета",
	"checkup.network.ok":           "подключено",
	"checkup.network.ok_named":     "подключено: {net}",
	"checkup.internet.none":        "не отвечают ни Cloudflare, ни Google, ни Яндекс: {errs}",
	"checkup.internet.ok":          "отвечают {hosts} ({ms} мс)",
	"checkup.internet.only_home":   "отвечает только Яндекс ({ms} мс), а Cloudflare и Google нет: похоже, сеть пропускает только белый список",
	"checkup.host.yandex":          "Яндекс",
	"checkup.dns.ok":               "адреса сайтов находятся ({ms} мс)",
	"checkup.dns.fail":             "DNS сети не отвечает: {err}",
	"checkup.who":                  "«{name}»",
	"checkup.who_none":             "сервер",
	"checkup.server.none":          "сервер не выбран",
	"checkup.server.resolve_fail":  "{who}: адрес сервера не находится ({err})",
	"checkup.server.udp_no_ping":   "{who}: сервер работает по UDP, а ping здесь недоступен: жив ли он, скажет связь через VPN",
	"checkup.server.local_answer":  "{who}: за сервер ответил другой VPN на этом устройстве",
	"checkup.server.udp_silent":    "{who}: сервер работает по UDP и на ping не отвечает ({err}): многие серверы ping не пропускают",
	"checkup.server.port_fail":     "{who}: порт сервера не отвечает ({err})",
	"checkup.server.ping_ok":       "отвечает на ping",
	"checkup.server.port_ok":       "порт отвечает",
	"checkup.server.ok":            "{who}: адрес найден, {what} ({ms} мс)",
	"checkup.server.ok_doh":        "{who}: адрес найден, {what} ({ms} мс); DNS сети не знает имени сервера, адрес нашёлся через DNS over HTTPS",
	"checkup.tunnel.fail":          "запросы через сервер не проходят: {err}",
	"checkup.tunnel.ok":            "работает, задержка {ms} мс",
	"checkup.tunnel.slow":          "работает, но задержка большая: {ms} мс",
	"checkup.tunnel_dns.proxy":     "режим «только прокси»: адреса ищут сами программы",
	"checkup.tunnel_dns.fail":      "адреса сайтов не находятся: {err}",
	"checkup.tunnel_dns.ok":        "отвечает ({ms} мс)",
	"checkup.tunnel_dns.fakeip":    "отвечает сам туннель (Fake-IP), имена сайтов ищет VPN-сервер",
	"checkup.leak.no_service":      "сервис проверки bash.ws не ответил через VPN: утечку проверить не удалось",
	"checkup.leak.ok":              "утечки нет: DNS-запросы провайдер не видит",
	"checkup.leak.isp":             "часть DNS-запросов обрабатывает DNS провайдера: он видит, какие сайты открываются",
	"checkup.leak.foreign":         "часть DNS-запросов обрабатывают DNS-серверы не из страны VPN-сервера",
	"checkup.leak.bypass":          "проверка прошла мимо VPN: похоже, сервер пускает bash.ws напрямую",
	"checkup.leak.unknown":         "результат неточный: не удалось узнать адрес без VPN",
	"checkup.speed.busy":           "идёт тест скорости",
	"checkup.speed.fail":           "замер не удался: {err}",
	"checkup.speed.ok":             "загрузка ≈ {mbit} Мбит/с",
	"checkup.speed.slow":           "медленно: загрузка ≈ {mbit} Мбит/с",
	"checkup.direct.whitelist":     "напрямую отвечает только Яндекс: похоже, оператор пропускает только белый список",
	"checkup.direct.offline":       "интернет не отвечает",
	"checkup.direct.ok":            "проходят",
	"checkup.direct.unused":        "не используются: весь трафик идёт через VPN",
	"checkup.direct.blocked":       "за это подключение прямые соединения не проходили, а через VPN всё работало",
	"checkup.direct.whitelist_vpn": "известные сайты напрямую не отвечают, а через VPN работают: похоже, сеть пропускает только белый список",

	// The checkup's verdict: Code+".title" and Code+".advice".
	"checkup.srv":                           "Сервер «{name}»",
	"checkup.srv_none":                      "Сервер",
	"checkup.verdict.no_network.title":      "Нет сети",
	"checkup.verdict.no_network.advice":     "Устройство не подключено к сети. Включите Wi-Fi или мобильный интернет, проверьте кабель.",
	"checkup.verdict.tunnel_dns.title":      "DNS через VPN не отвечает",
	"checkup.verdict.tunnel_dns.advice":     "Соединение через сервер есть, а адреса сайтов не находятся. Переподключитесь; если не поможет — выберите другой сервер.",
	"checkup.verdict.direct_blocked.title":  "Оператор режет прямые соединения — включите «Всё через VPN»",
	"checkup.verdict.direct_blocked.advice": "Через VPN всё работает, а сайты, которые идут напрямую, не открываются: похоже, сеть пропускает только белый список или российские сайты отсюда недоступны. {advice}",
	"checkup.verdict.dns_direct.title":      "DNS сети не отвечает",
	"checkup.verdict.dns_direct.advice":     "Через VPN всё работает, а сайты, которые идут напрямую, не открываются: DNS сети не находит их адресов. Пустите всё через VPN или укажите в настройках свой DNS для прямых запросов.",
	"checkup.verdict.leak.title":            "Есть утечка DNS",
	"checkup.verdict.leak.advice":           "VPN работает, но часть DNS-запросов видна провайдеру. Подробности и что изменить — в проверке утечки DNS в настройках.",
	"checkup.verdict.whitelist_vpn.title":   "Похоже, оператор пропускает только белый список",
	"checkup.verdict.whitelist_vpn.advice":  "Через VPN всё работает, а напрямую отвечает только Яндекс: сайты, которые идут напрямую, могут не открываться. {advice}",
	"checkup.verdict.slow.title":            "VPN работает, но медленно",
	"checkup.verdict.slow.advice":           "Задержка большая или скорость низкая. Выберите сервер поближе или с меньшим пингом.",
	"checkup.verdict.ok.title":              "Всё работает",
	"checkup.verdict.ok.advice":             "Сеть, сервер и VPN в порядке. Если какой-то сайт не открывается, дело, скорее всего, в нём самом.",
	"checkup.verdict.offline.title":         "Нет интернета — проверьте Wi-Fi",
	"checkup.verdict.offline.advice":        "Сеть есть, но интернет не отвечает: дело в сети, а не в VPN. Проверьте Wi-Fi или мобильный интернет и баланс у оператора, перезагрузите роутер.",
	"checkup.verdict.server_dns.title":      "Адрес сервера не находится",
	"checkup.verdict.server_dns.advice":     "Имя сервера не находится в DNS: его убрали или переименовали. Обновите подписку или выберите другой сервер.",
	"checkup.verdict.server_down.title":     "{srv} не отвечает — выберите другой",
	"checkup.verdict.server_down.advice":    "Интернет работает, а сервер нет: он выключен или заблокирован.",
	"checkup.verdict.server_blocked.title":  "{srv} на связи, но VPN через него не работает",
	"checkup.verdict.server_blocked.advice": "Соединение с сервером блокируют или изменились его настройки. Обновите подписку, включите «Обход блокировок (DPI)» или выберите другой сервер.",
	"checkup.verdict.tunnel.title":          "Связь через VPN не проходит",
	"checkup.verdict.tunnel.advice":         "Не удалось понять, виноват сервер или сеть. Переподключитесь; если не поможет — выберите другой сервер.",
	"checkup.verdict.dns.title":             "DNS сети не отвечает",
	"checkup.verdict.dns.advice":            "Интернет есть, а адреса сайтов не находятся. Подключите VPN — адреса будет искать сервер; или укажите другой DNS в настройках сети.",
	"checkup.verdict.no_server.title":       "Сервер не выбран",
	"checkup.verdict.no_server.advice":      "Выберите сервер, чтобы подключиться.",
	"checkup.verdict.whitelist.title":       "Похоже, сеть пропускает только белый список",
	"checkup.verdict.whitelist.advice":      "Напрямую отвечает только Яндекс. VPN может не подключиться; если так — попробуйте другой сервер.",
	"checkup.verdict.connect_failed.title":  "Сеть и сервер отвечают, а подключиться не удалось",
	"checkup.verdict.connect_failed.advice": "Попробуйте подключиться ещё раз; если не выйдет — выберите другой сервер или отправьте отчёт в поддержку.",
	"checkup.verdict.ready.title":           "Сеть в порядке, VPN не подключён",
	"checkup.verdict.ready.advice":          "Интернет и сервер отвечают. Нажмите «Подключить».",

	// A subscription running out: Android's notifications while the app is
	// closed (mobile/subwarn.go), the same as the app's banners.
	"sub.name.local":         "Мои серверы",
	"sub.name.default":       "Подписка",
	"sub.expired.title":      "Подписка «{name}» закончилась",
	"sub.expired.body":       "Продлите её у провайдера: без этого серверы не работают.",
	"sub.today.title":        "Подписка «{name}» закончится сегодня",
	"sub.tomorrow.title":     "Подписка «{name}» закончится завтра",
	"sub.day.body":           "Продлите её у провайдера, чтобы VPN не отключился.",
	"sub.days.title":         "Подписка «{name}» закончится через {days} {days|день|дня|дней}",
	"sub.days.body":          "Продлите её у провайдера заранее.",
	"sub.traffic_over.title": "Трафик подписки «{name}» закончился",
	"sub.traffic_over.body":  "Докупите трафик у провайдера или дождитесь его обновления.",
	"sub.traffic_low.title":  "Трафик подписки «{name}» почти израсходован",
	"sub.traffic_low.body":   "Осталось {left} из {total}.",
	"unit.tb":                "{n} ТБ",
	"unit.gb":                "{n} ГБ",
	"unit.mb":                "{n} МБ",
	"unit.kb":                "{n} КБ",
}
